#include "LuaApi.h"

#include "../LuaRuntime/LuaStackGuard.h"

#include <CKDefines.h>
#include <CKObject.h>

namespace {

void SetEnumValue(lua_State *L, const char *name, int value) {
    lua_pushinteger(L, value);
    lua_setfield(L, -2, name);
}

void RegisterObjectFlags(lua_State *L) {
    lua_newtable(L);
    SetEnumValue(L, "INTERFACEOBJ", CK_OBJECT_INTERFACEOBJ);
    SetEnumValue(L, "PRIVATE", CK_OBJECT_PRIVATE);
    SetEnumValue(L, "INTERFACEMARK", CK_OBJECT_INTERFACEMARK);
    SetEnumValue(L, "FREEID", CK_OBJECT_FREEID);
    SetEnumValue(L, "TOBEDELETED", CK_OBJECT_TOBEDELETED);
    SetEnumValue(L, "NOTTOBESAVED", CK_OBJECT_NOTTOBESAVED);
    SetEnumValue(L, "VISIBLE", CK_OBJECT_VISIBLE);
    SetEnumValue(L, "NAMESHARED", CK_OBJECT_NAMESHARED);
    SetEnumValue(L, "DYNAMIC", CK_OBJECT_DYNAMIC);
    SetEnumValue(L, "HIERACHICALHIDE", CK_OBJECT_HIERACHICALHIDE);
    SetEnumValue(L, "UPTODATE", CK_OBJECT_UPTODATE);
    SetEnumValue(L, "TEMPMARKER", CK_OBJECT_TEMPMARKER);
    SetEnumValue(L, "ONLYFORFILEREFERENCE", CK_OBJECT_ONLYFORFILEREFERENCE);
    SetEnumValue(L, "NOTTOBEDELETED", CK_OBJECT_NOTTOBEDELETED);
    SetEnumValue(L, "APPDATA", CK_OBJECT_APPDATA);
    SetEnumValue(L, "SINGLEACTIVITY", CK_OBJECT_SINGLEACTIVITY);
    SetEnumValue(L, "LOADSKIPBEOBJECT", CK_OBJECT_LOADSKIPBEOBJECT);
    SetEnumValue(L, "NOTTOBELISTEDANDSAVED", CK_OBJECT_NOTTOBELISTEDANDSAVED);
    SetEnumValue(L, "PARAMETEROUT_SETTINGS", CK_PARAMETEROUT_SETTINGS);
    SetEnumValue(L, "PARAMETEROUT_PARAMOP", CK_PARAMETEROUT_PARAMOP);
    SetEnumValue(L, "PARAMETERIN_DISABLED", CK_PARAMETERIN_DISABLED);
    SetEnumValue(L, "PARAMETERIN_THIS", CK_PARAMETERIN_THIS);
    SetEnumValue(L, "PARAMETERIN_SHARED", CK_PARAMETERIN_SHARED);
    SetEnumValue(L, "PARAMETEROUT_DELETEAFTERUSE", CK_PARAMETEROUT_DELETEAFTERUSE);
    SetEnumValue(L, "PARAMMASK", CK_OBJECT_PARAMMASK);
    SetEnumValue(L, "BEHAVIORIO_IN", CK_BEHAVIORIO_IN);
    SetEnumValue(L, "BEHAVIORIO_OUT", CK_BEHAVIORIO_OUT);
    SetEnumValue(L, "BEHAVIORIO_ACTIVE", CK_BEHAVIORIO_ACTIVE);
    SetEnumValue(L, "IOTYPEMASK", CK_OBJECT_IOTYPEMASK);
    SetEnumValue(L, "IOMASK", CK_OBJECT_IOMASK);
    SetEnumValue(L, "BEHAVIORLINK_RESERVED", CKBEHAVIORLINK_RESERVED);
    SetEnumValue(L, "BEHAVIORLINK_ACTIVATEDLASTFRAME", CKBEHAVIORLINK_ACTIVATEDLASTFRAME);
    SetEnumValue(L, "BEHAVIORLINKMASK", CK_OBJECT_BEHAVIORLINKMASK);
    lua_setglobal(L, "CK_OBJECT_FLAGS");
}

void RegisterShowOptions(lua_State *L) {
    lua_newtable(L);
    SetEnumValue(L, "CKHIDE", CKHIDE);
    SetEnumValue(L, "CKSHOW", CKSHOW);
    SetEnumValue(L, "CKHIERARCHICALHIDE", CKHIERARCHICALHIDE);
    lua_setglobal(L, "CK_OBJECT_SHOWOPTION");
}

void Register3dEntityFlags(lua_State *L) {
    lua_newtable(L);
    SetEnumValue(L, "DUMMY", CK_3DENTITY_DUMMY);
    SetEnumValue(L, "FRAME", CK_3DENTITY_FRAME);
    SetEnumValue(L, "RESERVED0", CK_3DENTITY_RESERVED0);
    SetEnumValue(L, "TARGETLIGHT", CK_3DENTITY_TARGETLIGHT);
    SetEnumValue(L, "TARGETCAMERA", CK_3DENTITY_TARGETCAMERA);
    SetEnumValue(L, "IGNOREANIMATION", CK_3DENTITY_IGNOREANIMATION);
    SetEnumValue(L, "HIERARCHICALOBSTACLE", CK_3DENTITY_HIERARCHICALOBSTACLE);
    SetEnumValue(L, "UPDATELASTFRAME", CK_3DENTITY_UPDATELASTFRAME);
    SetEnumValue(L, "CAMERAIGNOREASPECT", CK_3DENTITY_CAMERAIGNOREASPECT);
    SetEnumValue(L, "DISABLESKINPROCESS", CK_3DENTITY_DISABLESKINPROCESS);
    SetEnumValue(L, "ENABLESKINOFFSET", CK_3DENTITY_ENABLESKINOFFSET);
    SetEnumValue(L, "PLACEVALID", CK_3DENTITY_PLACEVALID);
    SetEnumValue(L, "PARENTVALID", CK_3DENTITY_PARENTVALID);
    SetEnumValue(L, "IKJOINTVALID", CK_3DENTITY_IKJOINTVALID);
    SetEnumValue(L, "PORTAL", CK_3DENTITY_PORTAL);
    SetEnumValue(L, "ZORDERVALID", CK_3DENTITY_ZORDERVALID);
    SetEnumValue(L, "CHARACTERDOPROCESS", CK_3DENTITY_CHARACTERDOPROCESS);
    lua_setglobal(L, "CK_3DENTITY_FLAGS");
}

void RegisterRayIntersection(lua_State *L) {
    lua_newtable(L);
    SetEnumValue(L, "DEFAULT", CKRAYINTERSECTION_DEFAULT);
    SetEnumValue(L, "SEGMENT", CKRAYINTERSECTION_SEGMENT);
    SetEnumValue(L, "IGNOREALPHA", CKRAYINTERSECTION_IGNOREALPHA);
    SetEnumValue(L, "FIRSTCONTACT", CKRAYINTERSECTION_FIRSTCONTACT);
    lua_setglobal(L, "CK_RAYINTERSECTION");
}

} // namespace

void LuaApi::RegisterCKEnums(lua_State *state) {
    tas::lua::LuaStackGuard guard(state);
    RegisterObjectFlags(state);
    RegisterShowOptions(state);
    Register3dEntityFlags(state);
    RegisterRayIntersection(state);
}
